name: talkio  # Changed from talkio_frontend to talkio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  socket_io_client: ^3.0.2
  jwt_decode: ^0.3.1
  glassmorphism: ^3.0.0
  animated_text_kit: ^4.2.3
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  cached_network_image: ^3.4.1
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true